### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by galihap76** [mizzcode/rest-api-cars#1]
Gilaaa wis anggo TypeScript ah.

**Comment by mizzcode** [comment]
mumet gal wkwkkw

**Comment by galihap76** [comment]
> mumet gal wkwkkw

Apalah enyong esih stay PHP karo laravel.

**Comment by galihap76** [comment]
Kie koen temenan dah pan migrasi full JavaScript?

**Comment by mizzcode** [comment]
iya gal semoga bae bisa

**Comment by galihap76** [comment]
> iya gal semoga bae bisa

Terus PHP karo laravel e pimen? apa maning aplikasi kelas maju ne dewek. Kie ngko enyong tetap bah pan tak upgrade aplikasi kelas maju tapi enteni ana waktu karo yen wis upgrade laptop enyonge.

**Comment by mizzcode** [comment]
> Terus PHP karo laravel e pimen? apa maning aplikasi kelas maju ne dewek. Kie ngko enyong tetap bah pan tak upgrade aplikasi kelas maju tapi enteni ana waktu karo yen wis upgrade laptop enyonge.

esih sih, sing kelasmaju mungkin ngko gal nunggu ana waktu juga
